services:
  db:
    image: postgres:16
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - expense_pgdata:/var/lib/postgresql/data

volumes:
  expense_pgdata:
